server:
  servlet:
    contextPath: /rand

spring:
  application:
    name: rand
eureka:
  client:
    serviceUrl:
      defaultZone: http://internal.services.lab.trendmicroservices.sohamroy.me:8080/eureka/eureka/
  instance:
    hostname: internal.services.lab.trendmicroservices.sohamroy.me